// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2kMhONa2Cp-_-uIQ8ggFYWcKGHGv43kI',
    appId: '1:1028832534423:web:e8385f6a12b3d61859aed2',
    messagingSenderId: '1028832534423',
    projectId: 'mynotes-74e3b',
    authDomain: 'mynotes-74e3b.firebaseapp.com',
    storageBucket: 'mynotes-74e3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ5rrMCfCXGYEj9bKNV97hI6U_9MFqUh8',
    appId: '1:1028832534423:android:12c7b6d3696e6f4e59aed2',
    messagingSenderId: '1028832534423',
    projectId: 'mynotes-74e3b',
    storageBucket: 'mynotes-74e3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcTqSaEKfNn7NuIY28963Is4bC92PP73w',
    appId: '1:1028832534423:ios:4e40a0a4d6b51f7b59aed2',
    messagingSenderId: '1028832534423',
    projectId: 'mynotes-74e3b',
    storageBucket: 'mynotes-74e3b.appspot.com',
    iosClientId: '1028832534423-qa8o03tqupeb45fj3qfu3eog3fup5jgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcTqSaEKfNn7NuIY28963Is4bC92PP73w',
    appId: '1:1028832534423:ios:4e40a0a4d6b51f7b59aed2',
    messagingSenderId: '1028832534423',
    projectId: 'mynotes-74e3b',
    storageBucket: 'mynotes-74e3b.appspot.com',
    iosClientId: '1028832534423-qa8o03tqupeb45fj3qfu3eog3fup5jgd.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
